### ISSUE TITLE
Aussehen neue Webseite

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#1]
Das aktuelle System mit den Tabs, finde ich eigentlich ganz nett. Allerdings haben wir ja dann deutlich mehr Tabs.

`| Elektrotechnik (AMR) | Elektrotechnik (EET) | Elektrotechnik (GMM) | Elektrotechnik (IT) | Elektrotechnik (MEL) |  Informationssystemtechnik | Mechatronik | Regenerative Energiesysteme`

Da sollten wir schauen ob wir eine Alternative anbieten können. Eventuell sollten wir eine neue landing page auf der alle Verlinkungen sind und erst mit dem Aufruf des Links wird eine entsprechende HTML Seite generiert die die passenden Informationen anhand der index.json generiert! Ansonsten wären die Anforderungen

- Responsive Design (Stichwort: mobile Endgeräte)
- schlichtes Design (Eventuell noch ein Logo und eine Überschrift)

**Comment by lutz** [comment]
Die alte Seite lief ja soweit keine Frage aber das mit den Tabs sollten wir dennoch anschauen. Ob ein Menü da hilft müssen wir uns genau anschauen

**Comment by lutzbox** [comment]
Die alte Seite lief ja soweit keine Frage aber das mit den Tabs sollten wir dennoch anschauen. Ob ein Menü da hilft müssen wir uns genau anschauen

**Comment by flueders** [comment]
https://flueders.github.io/unilinks/#ist
hier mal ein erster Entwurf

Tabs halte ich für ungeeignet, wenn mehr Studiengänge hinzukommen. Die werden dann gerade auf kleineren Geräten entweder übereinander dargestellt (nimmt viel Platz weg), oder man muss seitlich scrollen (das ist auch nicht gerade nutzerfreundlich)
