### ISSUE TITLE
Farbschema

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#10]
![image](https://user-images.githubusercontent.com/26437097/48723197-45471980-ec26-11e8-9be2-4b6c447a0883.png)

Wir sollten überlegen welche Farben wir nutzen. Ich finde das Blau als Highlightfarbe passt nicht so gut zu den anderen. Eventuell könnte man wenn der Designcode steht auch über eine Light/Dark Theme Variante nachdenken!

@jklmnn Wie denkst du darüber?

**Comment by jklmnn** [comment]
Also ich würde mir irgendeinen Designguide raussuchen, z.Bsp. den von [material.io](https://material.io/design/color/the-color-system.html). Da wird erklärt welche Farbkombinationen man nehmen kann und unten gibt es auch eine übersicht mit Farben die kombinierbar sind. Abgesehen davon dass ich einen Blauton als Grundfarbe bevorzugen würde habe ich keine Präferenzen. Ich bin auch kein Designer, deswegen hab ich ja initial Bootstrap genommen ;)

**Comment by lutz** [comment]
Mein Vorschlag:

![image](https://user-images.githubusercontent.com/26437097/48913655-4623b980-ee79-11e8-963e-63203371f412.png)

wäre diese Farbkombination.

**Comment by flueders** [comment]
Gut, ich würde die Seite auf Semantic UI (https://semantic-ui.com/) umstellen, da gibt es auch das Material Design als Thema
