### ISSUE TITLE
Impressum | Haftungsausschluss

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#12]
Wir sollten vielleicht überlegen ob wir ein einfaches Impressum mit Haftungsausschluss machen, dass wir nicht für die Inhalte hinter den Links verantwortlich sind und die Benutzung der Webseite auf eigene Gefahr erfolgt.

Wie denkt ihr dazu @flueders @jklmnn ?

**Comment by jklmnn** [comment]
Ja, das ist eine gute Idee? Wer opfert sich für das Impressum? ;)
Also rechtlich gesehen sollten wir theoretisch kein Impressum benötigen, da wir keine gewerbliche Dienstleistung erbringen und auch keine wirtschaftlichen Vorteile haben (Werbung etc.).
Ansonsten bin ich für einen Haftungsausschluss.

**Comment by lutz** [comment]
Also so wie es aussieht braucht man als private Webseite kein Impressum, solange keine Werbung, Dienstleistung usw erfolgt [Quelle](https://www.impressum-generator.de/2016/11/impressumspflicht-private-homepage/) Allerings sollten wir darauf hinweisen dass wir nicht fur die Inhalte hinter den Links verantwortlich sind und die Benutzung auf eigene Gefahr hin erfolgt. Bei der erstmaligen Nutzung sollte es ein Banner oder so was geben und der Nutzer muss aktive zustimmen zu den Nutzungsbedingungen. @flueders Wie siehst du das?

**Comment by jklmnn** [comment]
Also ich bin gegen ein Banner. Ich würde das unten in der Seite verlinken, oder so neben den Daten, dass man es sieht wenn man die Daten auch sieht. Von mir aus ein kleines "Alle Angaben ohne Gewähr" als Link auf einen Haftungsausschluss direkt neben den Daten. Aber auf keinen Fall ein Banner und auch nicht bei der ersten Nutzung. Letzteres benötigt zusätzlich Cookies und dann sieht man das jedes mal wenn man z.Bsp keine Cookies an hat.

**Comment by lutz** [comment]
mhmm das mit dem Cookies ist ein Argument vielleicht kann man dieses  _Alle Angaben ohne Gewähr_ und den Link zwischen der Kopfzeile und den Daten platzieren, dass wäre vll ein prominenter Platz.

**Comment by flueders** [comment]
Ich würde einen sehr dezenten Hinweis im Footer anbringen, dass die Seite nur Inhalte von Dritten verlinkt und wir daher nicht für die verlinkten Seiten verantwortlich sind.
Ein Haftungsausschluss ist heutzutage eigentlich nicht mehr üblich (wahrscheinlich rechtlich auch nicht notwendig)
Da wir sowieso nicht unsere Daten in Form eines Impressums angeben, können wir auch nicht haftbar gemacht werden (wie denn auch?;))
Der Hinweis ist wenn überhaupt für unsere Nutzer sinnvoll, vorallem sollte darauf hingewiesen werden dass die Links alt oder falsch sein können

**Comment by lutz** [comment]
@flueders Du kannst es ja in dein Entwurf mal mit einbauen, dann schaue ich mal drauf

**Comment by flueders** [comment]
![disclaimer](https://user-images.githubusercontent.com/26957052/50173658-63249e80-02f8-11e9-8aed-14fadb074961.PNG)

diesen Hinweis habe ich am Ende der Seite eingefügt, der Text kann auch noch geändert werden

**Comment by lutz** [comment]
sieht nett aus
