### ISSUE TITLE
Mitarbeit fördern

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#13]
**Vorschlag**

Bei allen Einträgen wo es noch keine URL gibt, verweisen wir standardmäßig auf eine HTML Page nach dem Motto: _Upps, zu diesem EIntrag fehlt der Link, du kannst uns gerne helfen ihn nachzutragen, weitere Infos hier_ oder so!

Was haltet ihr davon @jklmnn @flueders ?

**Comment by jklmnn** [comment]
Finde ich gut, generell ist Nachwuchs nicht falsch ;)

**Comment by flueders** [comment]
Ich habe erstmal eine sehr provisorische Mithelfen-Seite angelget. Dort könnte man noch die Prozedur mit Issue anlegen, etc. erklären.

**Comment by lutz** [comment]
Diskussion #17
