### ISSUE TITLE
Website-Icon / Logo

### ISSUE THREAD

**Issue by flueders** [unilinks/unilinks.github.io#14]
Ist das Logo schon zur Verwendung freigegeben?
Ich würde vorschlagen, dass wir als Favicon nur das Symbol (also ohne den Schriftzug "unilinks")  verwenden, da das auf die kleine Größe nicht mehr erkennbar ist.

**Comment by lutz** [comment]
So lange wir nichts besseres haben, können wir das gerne nehmen.

**Comment by lutz** [comment]
@flueders Wenn du mir alle verwendeten Farbcode hier schreibst, würde ich auch nochmal schauen ob man den aktuellen Farbverlauf des Logos vielleicht an das verwendete Grün anpasst

**Comment by lutz** [comment]
@flueders Ein Vorschlag: Statt das komplette Logo zu verwenden vielleicht nur wie hier:

![unbenannt-1](https://user-images.githubusercontent.com/26437097/50289639-b8cc8880-0469-11e9-8b62-bf2c3da751c2.jpg)

Das Icon in der Selektionsfarbe:

![favicon](https://user-images.githubusercontent.com/26437097/50289649-be29d300-0469-11e9-96d3-5f35c9df2a37.png)

**Comment by lutz** [comment]
Und das Zeichen das als Favicon auch nutzen. @flueders @jklmnn Was denkt ihr?

**Comment by jklmnn** [comment]
Sieht gut aus.

**Comment by flueders** [comment]
Gut, wird so verwendet.
