### ISSUE TITLE
Link für Fallback prominenter platzieren

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#15]
[Quelle:](https://github.com/unilinks/unilinks.github.io/issues/5)
> Hmm, aber die Fallbackversion ist doch nur für den Fall, dass überhaupt keine Daten geladen werden (weil das Javascript nicht kompatibel ist). In dem Fall wird die Anzeige auch nicht mit irgendwas überschrieben, da dann quasi nichts funktioniert.
> Ich könnte natürlich den Link auch ins Menü setzen, halte das aber nicht für notwendig

**Comment by flueders** [comment]
da die wenigsten überhaupt die Fallbackvariante verwenden müssen, und in dem Fall der Link aus meiner Sicht schon sehr prominent angezigt wird, schließe ich das Issue mal
