### ISSUE TITLE
Überschreibung Id

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#16]
@flueders ist es notwendig für das Scrollen zu einem Bereich die Id des Studienganges 
`index.html#ist` -> `index.html#sec-0` zu überschreiben?

**Ablauf**
1.  Seite wird erstmalig durch Nutzer aufgerufen
2. Nutzer wählt einen Studiengang (Studiengangs-Id ist in der URL)
3. Nutzer wählt einen Abschnitt aus (Studiengangs-Id wird überschrieben)
4. Nutzer speichert sich die URL ab um den Auswahlprozess nicht mehr zu haben

**Problem**
Gespeicherte URL führt nicht mehr zur gewählten Studiengang.

Frage ein Bug oder eher ein Missing Feature?

**Comment by flueders** [comment]
Das hatte ich dir vor einiger Zeit schonmal geschrieben. Das Problem liegt darin, dass die scrollspy-funktion von bootstrap nur mit Ankern arbeitet (d.h. man kann da z.B. nicht die `window.scrollTo` Methode verwenden). Letztlich reicht es doch, wenn man sich, mit dem richtigen Link ein Lesezeichen setzt, danach ist es doch egal wenn das überschrieben wird...

**Comment by lutz** [comment]
Ich stelle es mal zurück und wir schauen ob es dem Nutzer ersichtlich ist! Wenn alle sich den Link falsch speichern und es Beschwerden gibt gehen wir das ganze einfach nochmal an.
