### ISSUE TITLE
Umbenennung der Organisation

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#2]
Sorry dass ich noch mal Arbeit fabriziere. Unsere Organisation heißt statt `unlinksproject` jetzt nur noch `unilinks`. Ich habe den Github Support gebeten Kontakt mit dem Nutzer gleichen Namens auf zu nehmen und zu fragen ob wir den Namen haben können (der Nutzer hatte keine E-Mail hinterlegt) Da nach der `Name Squatting Policy` der Nutzer als **inaktiv** galt, haben sie den Benutzernamen für alle wieder freigeschaltet. Das habe ich einfach schnell für uns genutzt. Natürlich müssen jetzt die Github Pages und irgendwelche statische links angepasst werden, aber so ist dass denke ich besser!

- [x] Umbenennung Organisation
- [x] Umbenennung Repository der GitHub Page
- [x] Anpassung Links

Edit:

@jklmnn Sorry das ich die Page mit der Umbenennung gekillt habe. Das ist echt Mist dass er das nicht automatisch erkennt. Ein bisschen verstehe ich jetzt deine Abneigung gegen Umbenennung!

Edit 2: Okay jetzt geht die Seite wieder und der finale Link [https://unilinks.github.io](https://unilinks.github.io) geht nun auch wieder korrekt

**Comment by jklmnn** [comment]
Ich hab jetzt die restlichen Links die noch auf die Seite verweisen gefixt (jkliemann.de/unilinks.html, das wird noch von vielen verwendet weil das ursprünglich mal da lag). Ansonsten finde ich es gut, dass wir den Namen akquirieren konnten.

**Comment by lutz** [comment]
Ja da hätten wir echt Glück. Die ursprüngliche Seite bzw. die Weiterleitung würde ich so lange lassen bis die Version 2 verfügbar ist und wir aktiv dafür Werbung gemacht haben.

**Comment by jklmnn** [comment]
Also https://unilinks.github.io ist bereits in production. Und ursprüngliche Links müssen wir immer so lassen, bzw weiterleiten.

**Comment by lutz** [comment]
Das ist klar ich meine wenn wir Version 2 in Produktion geben (also mit allen Studiengängen oder zum großen Teil) das wir dann ja aktiv Werbung machen können und dort wird ja ja dann immer die neue URL genannt. Danach könntest du ja überlegen die Weiterleitung von der ursprünglichen Seite (jkliemann...) zu streichen.

**Comment by jklmnn** [comment]
Wenn ihr dafür Werbung macht sollt ihr natürlich den neuen Link nehmen. Aber die Weiterleitung lasse ich trotzdem, kostet ja nichts, und irgendwer hat immernoch einen alten Link ;)

**Comment by lutz** [comment]
Deswegen auch die Möglichkeitsform XD
