### ISSUE TITLE
Icon Auswahl

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#3]
- [x] Organisation | Webseite
- [x] Team **developers**

**Comment by jklmnn** [comment]
Ich würde wenn dann ein Icon machen, dass Orga und Webseite beide haben. Und wieso braucht ein Team ein Icon?

**Comment by lutz** [comment]
Orga und Webseite können gerne das gleuche nutzen. Ich finde die Standardicons von Github einfach nicht doll, da ist doch so ein nettes Icon ein nettes Gimmik. :D

**Comment by lutz** [comment]
Ich bin wie man sieht kein Designer, aber bis wir ein vernünftiges Logo haben oder jemanden finden der dahingehend besser geeignet ist, habe ich einfach mal ein Logo erstellt. 

<img width="195" alt="unilinks" src="https://user-images.githubusercontent.com/26437097/48314504-dbe25d80-e5ca-11e8-96e8-2348215bb97b.png">

<img width="195" alt="unilinks-developers" src="https://user-images.githubusercontent.com/26437097/48314505-dbe25d80-e5ca-11e8-88c2-5bad79185584.png">

Auf Anraten meiner Frau, hier noch eine Variante für das Teamlogo wo das Link Symbol auftauscht, um den Wiedererkennungswert zu steigern!

<img width="195" alt="unilinks-developers 2" src="https://user-images.githubusercontent.com/26437097/48315938-e3126700-e5dc-11e8-80e8-a56a06c79d86.png">


@jklmnn @flueders Was haltet ihr davon?

**Comment by lutz** [comment]
Ich stelle das mal temporär rein.

**Comment by jklmnn** [comment]
Sorry, dass da von mir nichts kam, ich hab grad kaum freie Kapazitäten. Ich finde das erste Logo am besten.
@lutz Ich finde es sinnvoll wenn man nur die Leute an ein Issue assigned die auch daran Arbeiten (im Sinne von die Aufgabe erledigen, nicht im Sinne von an der Diskussion teilnehmen). Da ich aktuell z.Bsp. an keinem Issue aktiv arbeite unassigne ich mich jetzt mal überall. Wenn jemand auf die Diskussion selbst hingewiesen werden soll reicht ein mention in den Kommentaren (so wie du es ja jetzt schon machst).
(Ich hab das mal hier rein geschrieben weil ich deswegen kein eigenes Issue aufmachen will).
EDIT: Das Webseitendesign wäre z.Bsp. so ein fall wo man sinnvollerweise nur flueders assignen würde, da er das ja macht.
