### ISSUE TITLE
Webseitendesign 2.0

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#5]
Da GitHub trotz Anfrage per E-Mail das Problem mit dem alten Issue (#1) nicht gelöst hat, habe ich es geschlossen und wir diskutieren einfach in diesem zum zukünftigen Aussehen. 

@jklmnn : @flueders hat mal angefangen das Design zu überarbeiten. Du findest es [hier](https://flueders.github.io/unilinks/). Da einige ältere Browser von Mobiltelefonen mit den neueren Techniken Probleme haben haben wir folgenden Vorschlag. Unter [unilinks.github.io](https://unilinks.github.io/#mel) wird die neue Webseite verfügbar sein und unter [https://unilinks.github.io/old/]() wird das alte Design so wie es jetzt ist, aber mit Unterstützung des neuen Datenformataufbaus abrufbar sein. So haben wir quasi eine Fallback Strategie. Daher wäre die Migration durch folgende Schritte durchzuführen

1. Alte Webseite an die neue `index.json` anpassen
2. Projektcode unter `old` (oder wir wir es nennen mögen) als eigenes Projekt aufnehmen und über einen `gh-pages` Branch verfügbar machen
3. Die alte Webseite im `unilinks.github.io` Projekt in einen Branch `design` überführen
4. Design entwickeln

**Comment by jklmnn** [comment]
Ich hab es mir grad mal angeschaut, sieht ganz gut aus. Ich hab aber zwei Fragen dazu:
 - Welche alten Browser/Mobiltelefone funktionieren nicht?
 - Wäre es möglich den ausgewählten Studiengang in der UI anzuzeigen? Wenn ich IST auswähle, dann sehe ich nur anhand der URL dass ich gerade bei IST bin.

**Comment by lutz** [comment]
Im `dev`-Branch habe ich mal den alten Parser an das neue Datenformat angepasst. Mit den Tabs sieht das jetzt nicht so doll aus, aber das wird schon mal gehen!

@flueders @jklmnn Wenn ihr es testen wollt müsst ihr in der `getTag(id)` Methode den Code auskommentieren und `return "18.w.3.dev";` als Rückgabewert definieren, so dass ihr ein Release vom `dev`-Branch bekommt. Wenn aus eurer Sicht nichts dagegen spricht, würde ich als nächstes schon ganz gerne umstellen, auch wenn das mit den Tabs bescheiden aussieht. Gerade weil es nur ein Fallback ist müssen wir meiner Meinung nach nicht mehr groß das anpassen. Wenn ihr das auch so seht, würde ich einen Merge in den `master` machen und anschließen einen `design` Branch anlegen, mit dem @flueders arbeiten kann. Dann braucht er seinen Fork nicht mehr und wir können dann auch leichter an den Code. Außerdem würde ich dann den letzten Stand des `master`-Branch als eigenes Projekt **old** anlegen um wie oben beschrieben den Zugriff dann auch den Zugriff zu haben, z.B. bei älteren Geräten.

@jklmnn Mein Blackberry Gerät kann mit dem neuen Design das Fabian erstellt hat z.B. nicht umgehen.

**Comment by lutz** [comment]
@flueders Es gibt nun den [design](https://github.com/unilinks/unilinks.github.io/tree/design). Ich würde dich bitten, das neue Design dort zu entwickeln, so dass wir nun auch Zugriff haben auf den Code.

**Comment by lutz** [comment]
Das Projekt `old` ist nun auch verfügbar!

**Comment by lutz** [comment]
@flueders Wir sollten schauen, dass wenn keine _url_ vorhanden ist, dass wir den Link als ausgegraut erscheinen!

**Comment by flueders** [comment]
Im design branch habe ich eine Version liegen, die das genau so macht. 
Diese funktioniert jetz übrigens schon mit der neuen Datenstruktur. Allerdings nur grob getestet....

**Comment by lutz** [comment]
**Bugs:**
- [x] #6
- [x] #7

**Enhancements:**
- [x] #8
- [x] #9
- [x] #10

**Comment by lutz** [comment]
[Designentwurf](https://flueders.github.io/unilinks.github.io/)

Mir sind folgende Dinge aufgefallen @flueders :
- Der Link zum GitHub Projekt fehlt
- Ich würde es besser finden wenn die `module-id` auf einer Zeile wie der Link ist, weil dann vertikal nicht so viel Platz gebraucht wird, was sich beim scrollen auf mobilen Endgeräten positiv auswirken würde.
- die Seite merkt sich nicht mehr den letzten Aufruf (Stichwort Cookie), daher muss man immer im Menü den Studiengang immer neu auswählen.
- du verwendest keine IDs mehr in der Browser-Adresse, daher scheint es auch nicht möglich sich auf seinen Studiengang einen Link setzen zu können.

Die Seite funktioniert bei mir  auf dem Desktop unter Chrome und Edge einwandfrei. Auf älteren Geräten aber nicht mehr. Dazu zählen im Moment:
- Blackberry 10 Browser (Blackberry Classic)
- Safari iOS 9 ( Ipad Mini 1. Generation)

Daher würde ich es gut finden wenn wir auf der Seite einen Link zur Fallback-Variante hätten.

**Comment by lutz** [comment]
Den aktuellen Stand finde ich schon mal gar nicht schlecht optisch. Folgende DInge sind mir dabei aufgefallen:
- [x] GitHub Link wird nicht in einem neuen Tab geöffnet, alle anderen Links schon
- [x] Einträge wo es keine URL gibt werden im Moment nicht 'disabled' angezeigt (zumindest wenn ich lokal debugge [=>Siehe Vorschlag](https://github.com/unilinks/unilinks.github.io/issues/13)
- [x] die modul-id sollte meiner Meinung nach in Klammern neben der Bezeichnung stehen
- [x] der Abstand zwischen den Links sollte geringer sein

![image](https://user-images.githubusercontent.com/26437097/50017504-88e63680-ffcc-11e8-93e7-b6260f562801.png)

- [x] der Link zum Fallback lautet `https://unilinks.github.io/old` nicht `https://unilinks.github.io/fallback`

**Comment by lutz** [comment]
@flueders Eine Sache ist mir im aktuellen Entwurf noch aufgefallen. Der Link zur alten Version bei Darstellungsproblemen wird nirgendswo mehr angezeigt sobald man einen Studiengang ausgewählt hat.  Ob mann aber Darstellungsprobleme hat weiß man ja erst sobald man es ausprobiert hat, also einen Studiengang gewählt hat und dass man sich den Link merkt halte ich für unwahrscheinlich. Vielleicht sollte man das auch auf den einzelnen Webseiten noch irgendwie unterbringen

**Comment by flueders** [comment]
#15 
Hmm, aber die Fallbackversion ist doch nur für den Fall, dass überhaupt keine Daten geladen werden (weil das Javascript nicht kompatibel ist). In dem Fall wird die Anzeige auch nicht mit irgendwas überschrieben, da dann quasi nichts funktioniert.
Ich könnte natürlich den Link auch ins Menü setzen, halte das aber nicht für notwendig

(Update:) Ich stelle es mal zurück und ich schaue es mir an wenn ich es nochmal teste!

**Comment by lutz** [comment]
![image](https://user-images.githubusercontent.com/26437097/50206705-8721c780-036c-11e9-9f86-e42816d3de50.png)

Der Link zu GitHub fehlt noch, und optisch müsste es noch etwas aufgehübscht werden.
z.B. mehr Rand nach oben, vielleicht so ein dreieckiges  Verkehrschild mit einem Ausrufezeichen oder sowas.

**Comment by lutz** [comment]
@flueders 
**Kleinere Designsachen**
- [ ] ~Modulname und Modulnummer sind nicht auf einer Linie (siehe Bild 1)~
- [ ] ~Farbe der Lehrveranstaltung (disabled) sollte die Gleiche sein wie die Standardfarbe des Modulnamens (siehe Bild 2)~
- [ ] ~Logo und Text sollte im Header vertikal zentriert zu einander sein (siehe Bild 3)~
- [ ] ~Unilinks und Studiengänge sollte auf einer Linie sein (siehe Bild 4)~

_Bild 1_
![image](https://user-images.githubusercontent.com/26437097/50352001-2d73f580-0544-11e9-8426-efc2d58e8301.png)

_Bild 2_
![image](https://user-images.githubusercontent.com/26437097/50352152-9c514e80-0544-11e9-9a9a-2b7d25d8974c.png)

_Bild 3_
![image](https://user-images.githubusercontent.com/26437097/50352394-5943ab00-0545-11e9-9cc4-1c3b348da7c5.png)

_Bild 4_
![image](https://user-images.githubusercontent.com/26437097/50352524-bf303280-0545-11e9-8947-c730289040b7.png)

**Comment by lutz** [comment]
@flueders muss als Favicon das `ICO` Format genutzt werden? Bei `PNG` hätten wir noch die Transparenz des Logos!

**Comment by flueders** [comment]
Also ich habe das mit dem Icon angepasst. Dass der Titel und die Menüeinträge nicht auf einer Linie sind, ist bei Bootstrap so vorgegeben (vermutlich richten die den Text nach den vertikalen Mitten aus, [siehe](https://getbootstrap.com/docs/4.0/components/navbar/#supported-content) ) Stört mich aber auch nicht.
Die Links, die disabled sind, sind doch schon inhaltlich etwas anderes als die Ergänzungen (Modulname, etc.). Warum sollten die dann in der selben Farbe erscheinen? Bootstrap unterscheided hier gleich drei verschiedene [Grautöne](https://getbootstrap.com/docs/4.0/utilities/colors/): secondary, dark, muted. Diese sollte man dann auch an geeigneter Stelle einsetzten können ;)

Generell: ich bin gern offen für Feedback, aber ich finde man sollte sich an solchen Kleinigkeiten nicht unnötig aufhalten... ;)

Das ico-Format hat sich aus den Urzeiten des Internets durchgesetzt und ist heute immernoch Standard. Aber ich habe eine Version mit Transparenz hochgeladen

**Comment by lutz** [comment]
> Also ich habe das mit dem Icon angepasst. Dass der Titel und die Menüeinträge nicht auf einer Linie sind, ist bei Bootstrap so vorgegeben (vermutlich richten die den Text nach den vertikalen Mitten aus, siehe ) Stört mich aber auch nicht.

Okay

> Die Links, die disabled sind, sind doch schon inhaltlich etwas anderes als die Ergänzungen (Modulname, etc.). Warum sollten die dann in der selben Farbe erscheinen? Bootstrap unterscheided hier gleich drei verschiedene Grautöne: secondary, dark, muted. Diese sollte man dann auch an geeigneter Stelle einsetzten können ;)

Es sieht harmonischer aus, aber lassen wir das mit den Kleinigkeiten

Meiner Meinung nach würde ich sagen dass es vorläufig erst mal so passt. Anpassungen können wir immer machen. Eine letzte Aufgabe habe ich aber noch für dich @flueders . Bitte füge auf der provisorischen Hilfeseite bei _GitHub_  noch einen Link hinzu so wie es bereits im Footer der anderen Seiten ist. Das Design können wir gerne im neuen Jahr besprechen. Wenn das erledigt ist, würde ich dich bitten, den Merge nach `master` zu machen und den Branch `design` zu löschen, dass wir einen Stand für 2018 haben. Bitte beachte aber die `README.md` des aktuellen `master` branch nicht zu überschreiben. Der Rest ist egal. Vielen Dank erstmal für die Arbeit @flueders. Ich denke damit haben wir erstmal eine gute Seite für die Studenten geschaffen.
