### ISSUE TITLE
Sortierung der Dateien fehlerhaft

### ISSUE THREAD

**Issue by lutz** [unilinks/unilinks.github.io#6]
![image](https://user-images.githubusercontent.com/26437097/48722691-eb921f80-ec24-11e8-821a-cc16d2849d3e.png)

Die Sortierung der Bereiche ist  fehlerhaft.

**Comment by flueders** [comment]
Das Problem tritt auf, weil die Dateien anscheinend unterschiedlich schnell geladen werden. Ich werde das Script daher so umschreiben, dass die Daten erst zwischengespeichert werden. Dann dauert es aber u.U. etwas läner, ehe die Ansicht geladen wird

**Comment by flueders** [comment]
Im Design-Branch sollte das Problem mitlerweile behoben sein.
Ich habe mal einen fork erstellt, damit man das mal direkt im Browser testen kann: https://flueders.github.io/unilinks.github.io/
Wenn das so ist, würde ich das Issue schließen

**Comment by lutz** [comment]
Die Sortierung scheint im Moment zu passen.
